name: Trigger
on:
  push:
    branches:
      - main
env:
  GT_TOKEN: ${{ secrets.DEPLOY }}

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Deploy Action
        run: | 
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{env.GT_TOKEN}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Hugo-Carvalho/vitibrasil_api-blueprints/dispatches \
            -d '{"event_type":"prd","client_payload":{"unit":false,"integration":true}}'