name: Trigger
on:
  push:
    branches:
      - main
env:
  GT_TOKEN: ${{ secrets.DEPLOY }}

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Deploy Action
        run: |
          repo_owner="Hugo-Carvalho"
          repo_name="vitibrasil_api-blueprints"
  
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{env.GT_TOKEN}}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches